// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.xzj.g01.base.proto.base;

public final class BaseProtoBuffer {
  private BaseProtoBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StrProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string param = 1;
    /**
     * <code>optional string param = 1;</code>
     */
    boolean hasParam();
    /**
     * <code>optional string param = 1;</code>
     */
    java.lang.String getParam();
    /**
     * <code>optional string param = 1;</code>
     */
    com.google.protobuf.ByteString
        getParamBytes();
  }
  /**
   * Protobuf type {@code proto.StrProto}
   */
  public static final class StrProto extends
      com.google.protobuf.GeneratedMessage
      implements StrProtoOrBuilder {
    // Use StrProto.newBuilder() to construct.
    private StrProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StrProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StrProto defaultInstance;
    public static StrProto getDefaultInstance() {
      return defaultInstance;
    }

    public StrProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StrProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              param_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xzj.g01.base.proto.base.BaseProtoBuffer.internal_static_proto_StrProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xzj.g01.base.proto.base.BaseProtoBuffer.internal_static_proto_StrProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto.class, com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto.Builder.class);
    }

    public static com.google.protobuf.Parser<StrProto> PARSER =
        new com.google.protobuf.AbstractParser<StrProto>() {
      public StrProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StrProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StrProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string param = 1;
    public static final int PARAM_FIELD_NUMBER = 1;
    private java.lang.Object param_;
    /**
     * <code>optional string param = 1;</code>
     */
    public boolean hasParam() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string param = 1;</code>
     */
    public java.lang.String getParam() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          param_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string param = 1;</code>
     */
    public com.google.protobuf.ByteString
        getParamBytes() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        param_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      param_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getParamBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getParamBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.StrProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xzj.g01.base.proto.base.BaseProtoBuffer.internal_static_proto_StrProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xzj.g01.base.proto.base.BaseProtoBuffer.internal_static_proto_StrProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto.class, com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto.Builder.class);
      }

      // Construct using com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        param_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xzj.g01.base.proto.base.BaseProtoBuffer.internal_static_proto_StrProto_descriptor;
      }

      public com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto getDefaultInstanceForType() {
        return com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto.getDefaultInstance();
      }

      public com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto build() {
        com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto buildPartial() {
        com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto result = new com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.param_ = param_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto) {
          return mergeFrom((com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto other) {
        if (other == com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto.getDefaultInstance()) return this;
        if (other.hasParam()) {
          bitField0_ |= 0x00000001;
          param_ = other.param_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xzj.g01.base.proto.base.BaseProtoBuffer.StrProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string param = 1;
      private java.lang.Object param_ = "";
      /**
       * <code>optional string param = 1;</code>
       */
      public boolean hasParam() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string param = 1;</code>
       */
      public java.lang.String getParam() {
        java.lang.Object ref = param_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          param_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string param = 1;</code>
       */
      public com.google.protobuf.ByteString
          getParamBytes() {
        java.lang.Object ref = param_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          param_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string param = 1;</code>
       */
      public Builder setParam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string param = 1;</code>
       */
      public Builder clearParam() {
        bitField0_ = (bitField0_ & ~0x00000001);
        param_ = getDefaultInstance().getParam();
        onChanged();
        return this;
      }
      /**
       * <code>optional string param = 1;</code>
       */
      public Builder setParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        param_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.StrProto)
    }

    static {
      defaultInstance = new StrProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.StrProto)
  }

  public interface IntProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 param = 1;
    /**
     * <code>optional int32 param = 1;</code>
     */
    boolean hasParam();
    /**
     * <code>optional int32 param = 1;</code>
     */
    int getParam();
  }
  /**
   * Protobuf type {@code proto.IntProto}
   */
  public static final class IntProto extends
      com.google.protobuf.GeneratedMessage
      implements IntProtoOrBuilder {
    // Use IntProto.newBuilder() to construct.
    private IntProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IntProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IntProto defaultInstance;
    public static IntProto getDefaultInstance() {
      return defaultInstance;
    }

    public IntProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IntProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              param_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xzj.g01.base.proto.base.BaseProtoBuffer.internal_static_proto_IntProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xzj.g01.base.proto.base.BaseProtoBuffer.internal_static_proto_IntProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto.class, com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto.Builder.class);
    }

    public static com.google.protobuf.Parser<IntProto> PARSER =
        new com.google.protobuf.AbstractParser<IntProto>() {
      public IntProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IntProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IntProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 param = 1;
    public static final int PARAM_FIELD_NUMBER = 1;
    private int param_;
    /**
     * <code>optional int32 param = 1;</code>
     */
    public boolean hasParam() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 param = 1;</code>
     */
    public int getParam() {
      return param_;
    }

    private void initFields() {
      param_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, param_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, param_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.IntProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xzj.g01.base.proto.base.BaseProtoBuffer.internal_static_proto_IntProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xzj.g01.base.proto.base.BaseProtoBuffer.internal_static_proto_IntProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto.class, com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto.Builder.class);
      }

      // Construct using com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        param_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xzj.g01.base.proto.base.BaseProtoBuffer.internal_static_proto_IntProto_descriptor;
      }

      public com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto getDefaultInstanceForType() {
        return com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto.getDefaultInstance();
      }

      public com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto build() {
        com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto buildPartial() {
        com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto result = new com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.param_ = param_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto) {
          return mergeFrom((com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto other) {
        if (other == com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto.getDefaultInstance()) return this;
        if (other.hasParam()) {
          setParam(other.getParam());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xzj.g01.base.proto.base.BaseProtoBuffer.IntProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 param = 1;
      private int param_ ;
      /**
       * <code>optional int32 param = 1;</code>
       */
      public boolean hasParam() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 param = 1;</code>
       */
      public int getParam() {
        return param_;
      }
      /**
       * <code>optional int32 param = 1;</code>
       */
      public Builder setParam(int value) {
        bitField0_ |= 0x00000001;
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 param = 1;</code>
       */
      public Builder clearParam() {
        bitField0_ = (bitField0_ & ~0x00000001);
        param_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.IntProto)
    }

    static {
      defaultInstance = new IntProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.IntProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StrProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_StrProto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_IntProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_IntProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbase.proto\022\005proto\"\031\n\010StrProto\022\r\n\005param" +
      "\030\001 \001(\t\"\031\n\010IntProto\022\r\n\005param\030\001 \001(\005B.\n\033com" +
      ".xzj.g01.base.proto.baseB\017BaseProtoBuffe" +
      "r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_StrProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_StrProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_StrProto_descriptor,
              new java.lang.String[] { "Param", });
          internal_static_proto_IntProto_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_IntProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_IntProto_descriptor,
              new java.lang.String[] { "Param", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
